# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('appaterno', models.CharField(max_length=15)),
                ('apmaterno', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Profecion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprofecion', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='profecion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dper.Profecion'),
        ),
    ]
